### PR TITLE
Turning signup view to class-based view

### PR DESCRIPTION
**Pull request by italopaiva**
Changing the signup view to a class-based view on accounts/views.py.

Signed-off-by: Italo Paiva <italosensei@hotmail.com>
Signed-off-by: Emiliemorais <emilie.mo@hotmail.com>

### CODE REVIEW

**Comment by chaws** [comment]
Good refactoring guys, but what would be the main reason for it?

**Comment by italopaiva** [comment]
@chaws, we were applying clean code techniques, and we saw that the signup view wasn't using class-based views, it were checking if the request method was POST or GET and then doing the specific staff for each one. So we created a class-based view and created a method to each request method type to make the code "more clean". I think we fixed another things too.

**Comment by italopaiva** [comment]
@chaws, we were applying clean code techniques, and we saw that the signup view wasn't using class-based views, it were checking if the request method was POST or GET and then doing the specific staff for each one. So we created a class-based view and created a method to each request method type to make the code "more clean". I think we fixed another things too.

**Comment by chaws** [comment]
Gotcha!! I'm merging this as soon as I'm done with other MRs. Are you planning to do more refactoring to clean up code some time later?

**Pull request merged**
