### PR TITLE
Behave acceptance tests

### PR DESCRIPTION
**Pull request by gabrielssilva**
Acceptance tests for:
- Sign up
- Sign in
- Edit profile

Also, added steps necessary to run behave tests to the README

### CODE REVIEW

**Comment by gabrielssilva** [comment]
The build is failing because `behave_django` is now listed in `settings.py` as a dependency. What should we do?

**Comment by lucasmoura** [comment]
@gabrielssilva Maybe the problem is the fact that test/colab_settings.py is already adding behave_django to the INSTALLED_APPS variable ? I don't know for sure if that is the problem, but maybe it is worth checking it out :)

**Comment by lucaskanashiro** [comment]
@lucasmoura +1 :)

**Comment by gabrielssilva** [comment]
Yeah, that's the issue. We listed behave_django in INSTALLED_APPS to run it with `colab-admin behave` instead of `python setup.py behave_tests`. We will remove it from `colab/seetings.py` and stick WITH `setup.py`.

Although, as pointed in https://github.com/behave/behave/issues/310, there is a bug when when using `setup.py` to run the tests with behave <=1.2.5 (currently available in pypi). Installing the edge release fixes the problem, but the tests are failing for some reason.

We will check it out and update the documentation.

**Comment by chaws** [comment]
Awesome work guys!

**Pull request merged**
