### PR TITLE
Fix solr boosting

### PR DESCRIPTION
**Pull request by lucaskanashiro**
Add some relevance in search. Matches in title have precedence than description.

@chaws could you review it?

### CODE REVIEW

**Comment by lucaskanashiro** [comment]
Matches in author field have more precedence than description too.

**Comment by chaws** [comment]
I'm on it

**Comment by chaws** [comment]
Just adding a little bit of understanding on that:
dismax: https://cwiki.apache.org/confluence/display/solr/The+DisMax+Query+Parser
edismax: https://cwiki.apache.org/confluence/display/solr/The+Extended+DisMax+Query+Parser

**Comment by chaws** [comment]
@lucaskanashiro , @GustJc would you have any scenario that I can try here?

**Comment by lucaskanashiro** [comment]
@chaws depends on the data that you imported to database. Basically, when you search something you should see first that matches in title, second in author, third in decription and so on. You just need to import data from other tools (noosfero and colab), index the data (of course you must run solr's service) and search something.

**Comment by chaws** [comment]
Got it, apparently edismax wasn't working properly when prioritizing tittle over contents: https://wiki.apache.org/solr/SolrRelevancyFAQ, and since we're not crafting any complex queries that require edismax, sticking to dismax seems to be good enough.

**Pull request merged**
